# ============================================================
# StudySphere AI - Email Service
# ============================================================

import os
import smtplib

from email.message import EmailMessage
from dotenv import load_dotenv


# ============================================================
# LOAD ENVIRONMENT VARIABLES
# ============================================================

load_dotenv()


# ============================================================
# SMTP CONFIGURATION
# ============================================================

SMTP_HOST = os.getenv(
    "SMTP_HOST",
    "smtp.gmail.com",
)

SMTP_PORT = int(
    os.getenv(
        "SMTP_PORT",
        "587",
    )
)

SMTP_USERNAME = os.getenv(
    "SMTP_USERNAME",
)

SMTP_PASSWORD = os.getenv(
    "SMTP_PASSWORD",
)

EMAIL_FROM = os.getenv(
    "EMAIL_FROM",
    SMTP_USERNAME,
)


# ============================================================
# VALIDATE SMTP CONFIGURATION
# ============================================================

def validate_email_configuration():
    """
    Validates the SMTP configuration.

    This function does not connect to the SMTP server.
    """

    missing = []

    if not SMTP_USERNAME:
        missing.append("SMTP_USERNAME")

    if not SMTP_PASSWORD:
        missing.append("SMTP_PASSWORD")

    if not EMAIL_FROM:
        missing.append("EMAIL_FROM")

    if missing:
        raise ValueError(
            "Missing email configuration: "
            + ", ".join(missing)
        )


# ============================================================
# SEND PASSWORD RESET EMAIL
# ============================================================

def send_password_reset_email(
    recipient_email: str,
    reset_link: str,
):
    """
    Sends a password reset email.

    Parameters:
        recipient_email:
            Email address of the user.

        reset_link:
            Password reset URL generated by auth.py.

    Returns:
        True when the email is successfully sent.
    """

    # --------------------------------------------------------
    # Validate inputs
    # --------------------------------------------------------

    if not recipient_email:
        raise ValueError(
            "Recipient email is required."
        )

    if not reset_link:
        raise ValueError(
            "Password reset link is required."
        )

    recipient_email = (
        recipient_email
        .strip()
        .lower()
    )

    # --------------------------------------------------------
    # Validate configuration
    # --------------------------------------------------------

    validate_email_configuration()

    # --------------------------------------------------------
    # Create Email
    # --------------------------------------------------------

    message = EmailMessage()

    message["Subject"] = (
        "Reset Your StudySphere Password"
    )

    message["From"] = EMAIL_FROM

    message["To"] = recipient_email

    # --------------------------------------------------------
    # Plain Text Email
    # --------------------------------------------------------

    text_content = f"""
Hello,

We received a request to reset your StudySphere password.

Click the link below to create a new password:

{reset_link}

This link is temporary and should only be used by you.

If you did not request a password reset, you can safely
ignore this email.

Regards,

StudySphere AI
AI Study Assistant
"""

    message.set_content(
        text_content.strip()
    )

    # --------------------------------------------------------
    # HTML Email
    # --------------------------------------------------------

    html_content = f"""
<!DOCTYPE html>

<html>

<head>
    <meta charset="UTF-8">

    <meta
        name="viewport"
        content="width=device-width, initial-scale=1.0"
    >

    <title>Reset Your Password</title>
</head>

<body
    style="
        margin:0;
        padding:0;
        background:#f5f7fb;
        font-family:Arial, Helvetica, sans-serif;
        color:#1f2937;
    "
>

    <div
        style="
            width:100%;
            padding:40px 20px;
            box-sizing:border-box;
        "
    >

        <div
            style="
                max-width:560px;
                margin:0 auto;
                background:#ffffff;
                border-radius:16px;
                overflow:hidden;
                box-shadow:0 8px 30px rgba(0,0,0,0.08);
            "
        >

            <!-- Header -->

            <div
                style="
                    padding:32px;
                    background:#111827;
                    color:#ffffff;
                    text-align:center;
                "
            >

                <div
                    style="
                        font-size:28px;
                        font-weight:700;
                        letter-spacing:-0.5px;
                    "
                >
                    StudySphere
                </div>

                <div
                    style="
                        margin-top:8px;
                        font-size:14px;
                        color:#d1d5db;
                    "
                >
                    AI Study Assistant
                </div>

            </div>


            <!-- Content -->

            <div
                style="
                    padding:36px 32px;
                "
            >

                <h1
                    style="
                        margin:0 0 16px;
                        font-size:24px;
                        line-height:1.3;
                        color:#111827;
                    "
                >
                    Reset your password
                </h1>

                <p
                    style="
                        margin:0 0 16px;
                        font-size:15px;
                        line-height:1.7;
                        color:#4b5563;
                    "
                >
                    We received a request to reset your
                    StudySphere account password.
                </p>

                <p
                    style="
                        margin:0 0 28px;
                        font-size:15px;
                        line-height:1.7;
                        color:#4b5563;
                    "
                >
                    Click the button below to create a new
                    password.
                </p>


                <!-- Button -->

                <div
                    style="
                        text-align:center;
                        margin:30px 0;
                    "
                >

                    <a
                        href="{reset_link}"
                        style="
                            display:inline-block;
                            padding:14px 26px;
                            background:#111827;
                            color:#ffffff;
                            text-decoration:none;
                            border-radius:10px;
                            font-size:15px;
                            font-weight:600;
                        "
                    >
                        Reset Password
                    </a>

                </div>


                <!-- Link fallback -->

                <p
                    style="
                        margin:28px 0 8px;
                        font-size:13px;
                        color:#6b7280;
                    "
                >
                    If the button does not work, copy and
                    paste this link into your browser:
                </p>

                <p
                    style="
                        margin:0;
                        padding:12px;
                        background:#f3f4f6;
                        border-radius:8px;
                        font-size:12px;
                        line-height:1.6;
                        word-break:break-all;
                        color:#4b5563;
                    "
                >
                    {reset_link}
                </p>


                <!-- Security notice -->

                <div
                    style="
                        margin-top:28px;
                        padding:16px;
                        background:#f9fafb;
                        border-radius:10px;
                        border:1px solid #e5e7eb;
                    "
                >

                    <p
                        style="
                            margin:0;
                            font-size:13px;
                            line-height:1.6;
                            color:#6b7280;
                        "
                    >
                        If you did not request a password
                        reset, you can safely ignore this email.
                    </p>

                </div>

            </div>


            <!-- Footer -->

            <div
                style="
                    padding:22px 32px;
                    border-top:1px solid #e5e7eb;
                    text-align:center;
                "
            >

                <p
                    style="
                        margin:0;
                        font-size:12px;
                        color:#9ca3af;
                    "
                >
                    © StudySphere AI
                </p>

                <p
                    style="
                        margin:6px 0 0;
                        font-size:12px;
                        color:#9ca3af;
                    "
                >
                    AI-powered learning assistant
                </p>

            </div>

        </div>

    </div>

</body>

</html>
"""

    message.add_alternative(
        html_content,
        subtype="html",
    )

    # --------------------------------------------------------
    # Send Email
    # --------------------------------------------------------

    print("=" * 60)
    print("[EMAIL] Preparing password reset email")
    print(f"[EMAIL] Recipient: {recipient_email}")
    print(f"[EMAIL] SMTP Host: {SMTP_HOST}")
    print(f"[EMAIL] SMTP Port: {SMTP_PORT}")
    print("=" * 60)

    try:

        # ----------------------------------------------------
        # Connect to SMTP server
        # ----------------------------------------------------

        with smtplib.SMTP(
            SMTP_HOST,
            SMTP_PORT,
            timeout=30,
        ) as server:

            # ------------------------------------------------
            # Enable TLS
            # ------------------------------------------------

            server.starttls()

            # ------------------------------------------------
            # Login
            # ------------------------------------------------

            server.login(
                SMTP_USERNAME,
                SMTP_PASSWORD,
            )

            # ------------------------------------------------
            # Send
            # ------------------------------------------------

            server.send_message(
                message
            )

        print(
            f"[EMAIL] Password reset email sent successfully "
            f"to {recipient_email}"
        )

        print("=" * 60)

        return True

    except smtplib.SMTPAuthenticationError as exc:

        print(
            "[EMAIL ERROR] SMTP authentication failed."
        )

        print(
            "[EMAIL ERROR]",
            repr(exc),
        )

        raise RuntimeError(
            "SMTP authentication failed. "
            "For Gmail, make sure you are using a "
            "Google App Password instead of your normal "
            "Gmail password."
        ) from exc

    except smtplib.SMTPException as exc:

        print(
            "[EMAIL ERROR] SMTP error occurred."
        )

        print(
            "[EMAIL ERROR]",
            repr(exc),
        )

        raise RuntimeError(
            "Unable to send password reset email."
        ) from exc

    except OSError as exc:

        print(
            "[EMAIL ERROR] Could not connect to SMTP server."
        )

        print(
            "[EMAIL ERROR]",
            repr(exc),
        )

        raise RuntimeError(
            "Unable to connect to the email server. "
            "Please check SMTP configuration and internet connection."
        ) from exc

    except Exception as exc:

        print(
            "[EMAIL ERROR] Unexpected email error."
        )

        print(
            "[EMAIL ERROR]",
            repr(exc),
        )

        raise RuntimeError(
            "Something went wrong while sending the email."
        ) from exc