# ============================================================
# StudySphere AI - ChromaDB Vector Store
# Production-ready document storage + semantic retrieval
# ============================================================

import hashlib
import math
import os
import re
from typing import Any, Dict, List, Optional, Sequence, Set, Tuple

import chromadb


# ============================================================
# CONFIGURATION
# ============================================================

BASE_DIR = os.path.dirname(
    os.path.dirname(
        os.path.abspath(__file__)
    )
)

CHROMA_DB_PATH = os.path.join(BASE_DIR, "chroma_db")

COLLECTION_PREFIX = "user_"

# ChromaDB add operations are batched to avoid very large requests.
BATCH_SIZE = 100

# None = do not reject semantic results only because of distance.
#
# This is intentionally disabled by default because OCR/scanned PDFs
# can produce noisier embeddings even when the result is relevant.
DEFAULT_MIN_DISTANCE = None

# Number of semantic candidates retrieved before optional reranking.
DEFAULT_SEARCH_RESULTS = 10

# Maximum number of chunks returned after ranking.
DEFAULT_MAX_RETURN_RESULTS = 10

# Page marker generated by pdf_utils.py / chunking.py.
PAGE_MARKER_PATTERN = re.compile(
    r"\[Page\s+(\d+)\]",
    re.IGNORECASE,
)

# Lightweight lexical tokenizer used only for retrieval diagnostics
# and optional reranking.
TOKEN_PATTERN = re.compile(
    r"[A-Za-z0-9_+-]+"
)

# Common English words that should not strongly influence lexical
# relevance scoring.
STOP_WORDS: Set[str] = {
    "a",
    "an",
    "and",
    "are",
    "as",
    "at",
    "be",
    "been",
    "being",
    "but",
    "by",
    "can",
    "could",
    "did",
    "do",
    "does",
    "for",
    "from",
    "has",
    "have",
    "how",
    "if",
    "in",
    "into",
    "is",
    "it",
    "its",
    "may",
    "might",
    "more",
    "most",
    "of",
    "on",
    "or",
    "should",
    "such",
    "than",
    "that",
    "the",
    "their",
    "there",
    "these",
    "this",
    "those",
    "to",
    "was",
    "were",
    "what",
    "when",
    "where",
    "which",
    "who",
    "why",
    "will",
    "with",
    "would",
}


# ============================================================
# CHROMADB CLIENT
# ============================================================

print()
print("=" * 72)
print("STUDYSPHERE CHROMADB")
print("=" * 72)
print(f"[VectorStore] Database path: {CHROMA_DB_PATH}")

os.makedirs(CHROMA_DB_PATH, exist_ok=True)

try:
    chroma_client = chromadb.PersistentClient(
        path=CHROMA_DB_PATH
    )
except Exception as error:
    print(
        "[VectorStore] Failed to initialize ChromaDB:",
        repr(error),
    )
    raise

print("[VectorStore] ChromaDB initialized successfully.")
print("=" * 72)
print()


# ============================================================
# INTERNAL VALIDATION HELPERS
# ============================================================

def _validate_user_id(user_id: int) -> int:
    """Validate and normalize the authenticated user ID."""

    try:
        user_id = int(user_id)
    except (TypeError, ValueError) as error:
        raise ValueError(
            "user_id must be a valid integer."
        ) from error

    if user_id <= 0:
        raise ValueError(
            "user_id must be greater than 0."
        )

    return user_id


def _clean_filename(filename: str) -> str:
    """Validate a PDF filename."""

    if filename is None:
        raise ValueError(
            "filename cannot be empty."
        )

    filename = str(filename).strip()

    if not filename:
        raise ValueError(
            "filename cannot be empty."
        )

    return filename


def _get_collection_name(user_id: int) -> str:
    """Return the isolated ChromaDB collection name for a user."""

    user_id = _validate_user_id(user_id)

    return (
        f"{COLLECTION_PREFIX}"
        f"{user_id}"
        f"_documents"
    )


def _safe_int(
    value: Any,
    default: int = 0,
) -> int:
    """Safely convert a value to integer."""

    try:
        return int(value)
    except (TypeError, ValueError):
        return default


def _safe_float(
    value: Any,
    default: float = 0.0,
) -> float:
    """Safely convert a value to float."""

    try:
        return float(value)
    except (TypeError, ValueError):
        return default


# ============================================================
# TEXT / TOKEN HELPERS
# ============================================================

def _normalize_text(text: Any) -> str:
    """
    Normalize whitespace without destroying page markers or
    meaningful document content.
    """

    if text is None:
        return ""

    text = str(text)

    # Normalize Windows and old-Mac line endings.
    text = text.replace("\r\n", "\n")
    text = text.replace("\r", "\n")

    # Normalize tabs.
    text = text.replace("\t", " ")

    # Keep newlines but collapse excessive spaces.
    text = re.sub(
        r"[ ]{2,}",
        " ",
        text,
    )

    # Collapse excessive blank lines.
    text = re.sub(
        r"\n{3,}",
        "\n\n",
        text,
    )

    return text.strip()


def _tokenize(text: str) -> Set[str]:
    """
    Tokenize text for lightweight lexical relevance scoring.

    This does NOT replace semantic embeddings.
    It only helps OCR-heavy queries where exact terminology
    can be important.
    """

    if not text:
        return set()

    tokens = {
        token.lower()
        for token in TOKEN_PATTERN.findall(
            str(text)
        )
    }

    return {
        token
        for token in tokens
        if len(token) >= 2
        and token not in STOP_WORDS
    }


def _calculate_lexical_overlap(
    query_tokens: Set[str],
    document: str,
) -> float:
    """
    Calculate query-token coverage inside a document.

    Example:
        Query: "multilevel inheritance"
        Document contains both terms
        -> high score
    """

    if not query_tokens:
        return 0.0

    document_tokens = _tokenize(document)

    if not document_tokens:
        return 0.0

    matched = query_tokens.intersection(
        document_tokens
    )

    return (
        len(matched)
        / max(len(query_tokens), 1)
    )


def _calculate_token_frequency_score(
    query_tokens: Set[str],
    document: str,
) -> float:
    """
    Small supporting lexical score based on repeated
    query terminology.

    This is intentionally capped so repeated OCR text cannot
    overpower semantic similarity.
    """

    if not query_tokens or not document:
        return 0.0

    document_tokens = [
        token.lower()
        for token in TOKEN_PATTERN.findall(
            str(document)
        )
    ]

    if not document_tokens:
        return 0.0

    document_token_set = set(document_tokens)

    matched_tokens = query_tokens.intersection(
        document_token_set
    )

    if not matched_tokens:
        return 0.0

    frequency_total = 0

    for token in matched_tokens:
        frequency_total += document_tokens.count(
            token
        )

    # Small bounded score.
    return min(
        frequency_total / max(len(document_tokens), 1),
        0.25,
    )


# ============================================================
# PAGE METADATA HELPERS
# ============================================================

def _extract_page_numbers(
    chunk: str,
) -> List[int]:
    """
    Extract every [Page N] marker from a chunk.
    """

    if not chunk:
        return []

    page_numbers: List[int] = []

    for value in PAGE_MARKER_PATTERN.findall(
        str(chunk)
    ):
        page = _safe_int(
            value,
            0,
        )

        if (
            page > 0
            and page not in page_numbers
        ):
            page_numbers.append(page)

    return page_numbers


def _build_page_metadata(
    chunk: str,
) -> Dict[str, Any]:
    """
    Build normalized page metadata for a chunk.
    """

    page_numbers = _extract_page_numbers(
        chunk
    )

    if not page_numbers:
        return {
            "page_number": 0,
            "page_numbers": "",
        }

    return {
        "page_number": page_numbers[0],
        "page_numbers": ",".join(
            str(page)
            for page in page_numbers
        ),
    }


# ============================================================
# EMBEDDING VALIDATION
# ============================================================

def _embedding_to_list(
    embedding: Sequence[float],
    index: int,
) -> List[float]:
    """
    Convert an embedding to a validated float list.
    """

    if embedding is None:
        raise ValueError(
            f"Embedding {index} cannot be None."
        )

    try:
        values = [
            float(value)
            for value in embedding
        ]
    except (TypeError, ValueError) as error:
        raise ValueError(
            f"Embedding {index} contains invalid values."
        ) from error

    if not values:
        raise ValueError(
            f"Embedding {index} cannot be empty."
        )

    for value in values:
        if not math.isfinite(value):
            raise ValueError(
                f"Embedding {index} contains "
                "NaN or infinite values."
            )

    return values


def _validate_embedding_dimensions(
    embeddings: Sequence[
        Sequence[float]
    ],
) -> int:
    """
    Ensure every embedding has the same dimension.
    """

    if not embeddings:
        raise ValueError(
            "Embeddings cannot be empty."
        )

    dimension = len(
        embeddings[0]
    )

    if dimension == 0:
        raise ValueError(
            "Embedding dimension cannot be zero."
        )

    for index, embedding in enumerate(
        embeddings
    ):
        if len(embedding) != dimension:
            raise ValueError(
                "Embedding dimension mismatch at "
                f"index {index}. "
                f"Expected {dimension}, "
                f"received {len(embedding)}."
            )

    return dimension


# ============================================================
# DETERMINISTIC CHUNK ID
# ============================================================

def _create_chunk_id(
    user_id: int,
    filename: str,
    chunk_index: int,
    chunk: str,
) -> str:
    """
    Create a deterministic and collision-resistant Chroma ID.

    The chunk index is included so two identical chunks appearing
    at different positions remain separate vectors.
    """

    raw_id = (
        f"{user_id}::"
        f"{filename}::"
        f"{chunk_index}::"
        f"{chunk}"
    )

    digest = hashlib.sha256(
        raw_id.encode("utf-8")
    ).hexdigest()

    return (
        f"{COLLECTION_PREFIX}"
        f"{user_id}_"
        f"{digest}"
    )


# ============================================================
# GET USER COLLECTION
# ============================================================

def get_collection(user_id: int):
    """
    Return the authenticated user's isolated ChromaDB collection.
    """

    collection_name = _get_collection_name(
        user_id
    )

    try:
        return chroma_client.get_or_create_collection(
            name=collection_name,
            metadata={
                "hnsw:space": "cosine",
                "user_id": str(user_id),
            },
        )

    except Exception as error:
        print(
            "[VectorStore] Unable to access collection:",
            repr(error),
        )

        raise RuntimeError(
            "Unable to access ChromaDB collection."
        ) from error


# ============================================================
# DELETE EXISTING DOCUMENT
# ============================================================

def _get_document_ids(
    collection,
    filename: str,
) -> List[str]:
    """
    Return all vector IDs belonging to one filename.
    """

    try:
        existing = collection.get(
            where={
                "filename": filename
            },
            include=["metadatas"],
        )

    except Exception as error:
        print(
            "[VectorStore] Failed to inspect "
            f"document '{filename}':",
            repr(error),
        )

        raise RuntimeError(
            "Unable to inspect existing document vectors."
        ) from error

    if not existing:
        return []

    return list(
        existing.get(
            "ids",
            [],
        ) or []
    )


def _delete_existing_document(
    collection,
    filename: str,
) -> int:
    """
    Delete all vectors for a filename.

    This makes re-uploading a PDF replace its old vectors
    rather than accumulating duplicates.
    """

    ids = _get_document_ids(
        collection,
        filename,
    )

    if not ids:
        return 0

    try:
        collection.delete(
            ids=ids
        )

        return len(ids)

    except Exception as error:
        print(
            "[VectorStore] Failed to remove "
            f"existing document '{filename}':",
            repr(error),
        )

        raise RuntimeError(
            "Unable to replace existing document vectors."
        ) from error


# ============================================================
# STORE CHUNKS
# ============================================================

def store_chunks(
    user_id: int,
    filename: str,
    chunks: Sequence[str],
    embeddings: Sequence[
        Sequence[float]
    ],
) -> int:
    """
    Replace all existing vectors for this filename and store
    the new chunk/embedding set.

    Public signature is intentionally preserved for main.py.
    """

    user_id = _validate_user_id(
        user_id
    )

    filename = _clean_filename(
        filename
    )

    if not chunks:
        raise ValueError(
            "chunks cannot be empty."
        )

    if not embeddings:
        raise ValueError(
            "embeddings cannot be empty."
        )

    if len(chunks) != len(
        embeddings
    ):
        raise ValueError(
            "Chunk count and embedding count "
            "must be identical."
        )

    # --------------------------------------------------------
    # Clean chunks
    # --------------------------------------------------------

    clean_chunks: List[str] = []

    for index, chunk in enumerate(
        chunks
    ):
        if chunk is None:
            raise ValueError(
                f"Chunk {index} cannot be None."
            )

        cleaned = _normalize_text(
            chunk
        )

        if not cleaned:
            raise ValueError(
                f"Chunk {index} cannot be empty."
            )

        clean_chunks.append(
            cleaned
        )

    # --------------------------------------------------------
    # Validate embeddings
    # --------------------------------------------------------

    clean_embeddings = [
        _embedding_to_list(
            embedding,
            index,
        )
        for index, embedding in enumerate(
            embeddings
        )
    ]

    embedding_dimension = (
        _validate_embedding_dimensions(
            clean_embeddings
        )
    )

    # --------------------------------------------------------
    # Logging
    # --------------------------------------------------------

    print()
    print(
        "[VectorStore] Preparing document:"
    )
    print(
        f"  User ID          : {user_id}"
    )
    print(
        f"  Filename         : {filename}"
    )
    print(
        f"  Chunks           : {len(clean_chunks)}"
    )
    print(
        f"  Embedding size   : "
        f"{embedding_dimension}"
    )

    collection = get_collection(
        user_id
    )

    # --------------------------------------------------------
    # Remove old vectors
    # --------------------------------------------------------

    deleted_count = (
        _delete_existing_document(
            collection=collection,
            filename=filename,
        )
    )

    if deleted_count:
        print(
            "[VectorStore] Removed "
            f"{deleted_count} old vector(s)."
        )

    # --------------------------------------------------------
    # Prepare Chroma records
    # --------------------------------------------------------

    ids: List[str] = []
    documents: List[str] = []
    metadatas: List[
        Dict[str, Any]
    ] = []

    for index, chunk in enumerate(
        clean_chunks
    ):
        chunk_id = _create_chunk_id(
            user_id=user_id,
            filename=filename,
            chunk_index=index,
            chunk=chunk,
        )

        page_metadata = (
            _build_page_metadata(
                chunk
            )
        )

        ids.append(
            chunk_id
        )

        documents.append(
            chunk
        )

        metadatas.append({
            "user_id": str(
                user_id
            ),
            "filename": filename,
            "chunk_index": index,
            "document_type": "pdf",
            "page_number": (
                page_metadata[
                    "page_number"
                ]
            ),
            "page_numbers": (
                page_metadata[
                    "page_numbers"
                ]
            ),
        })

        print(
            "[VectorStore] Chunk "
            f"{index + 1}: "
            f"pages="
            f"{page_metadata['page_numbers'] or 'unknown'} "
            f"| chars={len(chunk)}"
        )

    # --------------------------------------------------------
    # Store in batches
    # --------------------------------------------------------

    stored_count = 0

    try:
        for start in range(
            0,
            len(ids),
            BATCH_SIZE,
        ):
            end = min(
                start + BATCH_SIZE,
                len(ids),
            )

            collection.add(
                ids=ids[start:end],
                documents=documents[
                    start:end
                ],
                embeddings=clean_embeddings[
                    start:end
                ],
                metadatas=metadatas[
                    start:end
                ],
            )

            stored_count += (
                end - start
            )

            print(
                "[VectorStore] Stored batch: "
                f"{start + 1}-{end}"
            )

    except Exception as error:
        print(
            "[VectorStore] ChromaDB insertion failed:",
            repr(error),
        )

        # ----------------------------------------------------
        # Partial insertion cleanup
        # ----------------------------------------------------

        try:
            inserted_ids = ids[
                :stored_count
            ]

            if inserted_ids:
                collection.delete(
                    ids=inserted_ids
                )

                print(
                    "[VectorStore] Partial "
                    "insertion cleaned up."
                )

        except Exception as cleanup_error:
            print(
                "[VectorStore] Cleanup failed:",
                repr(cleanup_error),
            )

        raise RuntimeError(
            "Unable to store document vectors "
            "in ChromaDB."
        ) from error

    # --------------------------------------------------------
    # Final validation
    # --------------------------------------------------------

    if stored_count != len(
        clean_chunks
    ):
        raise RuntimeError(
            "Stored vector count does not "
            "match chunk count."
        )

    try:
        actual_count = (
            collection.count()
        )
    except Exception:
        actual_count = -1

    print(
        "[VectorStore] Document stored successfully."
    )

    print(
        "[VectorStore] Stored vectors "
        f"for this document: {stored_count}"
    )

    print(
        "[VectorStore] Total user collection "
        f"vectors: {actual_count}"
    )

    return stored_count


# ============================================================
# RETRIEVAL SCORING
# ============================================================

def _build_ranked_results(
    documents: List[str],
    metadatas: List[Dict[str, Any]],
    distances: List[float],
    ids: List[str],
    query_text: Optional[str],
) -> List[
    Tuple[
        float,
        int,
        Dict[str, Any],
    ]
]:
    """
    Build a combined retrieval ranking.

    Primary signal:
        Chroma semantic distance

    Secondary signal:
        lexical query-term coverage

    This is deliberately conservative:
    semantic similarity remains the main signal.
    """

    query_tokens = _tokenize(
        query_text or ""
    )

    ranked = []

    for index, document in enumerate(
        documents
    ):
        metadata = (
            metadatas[index]
            if index < len(metadatas)
            and metadatas[index]
            else {}
        )

        distance = (
            distances[index]
            if index < len(distances)
            else None
        )

        if distance is None:
            semantic_score = 0.0
        else:
            distance_value = _safe_float(
                distance,
                1.0,
            )

            # Cosine distance is generally smaller
            # for more similar vectors.
            #
            # Convert it to a bounded similarity-like
            # value for ranking only.
            semantic_score = max(
                0.0,
                1.0 - distance_value,
            )

        lexical_overlap = (
            _calculate_lexical_overlap(
                query_tokens,
                document,
            )
        )

        frequency_score = (
            _calculate_token_frequency_score(
                query_tokens,
                document,
            )
        )

        # Semantic score remains dominant.
        combined_score = (
            semantic_score * 0.80
            + lexical_overlap * 0.17
            + frequency_score * 0.03
        )

        ranked.append(
            (
                combined_score,
                index,
                {
                    "semantic_score": round(
                        semantic_score,
                        4,
                    ),
                    "lexical_overlap": round(
                        lexical_overlap,
                        4,
                    ),
                    "frequency_score": round(
                        frequency_score,
                        4,
                    ),
                    "distance": distance,
                    "id": (
                        ids[index]
                        if index < len(ids)
                        else None
                    ),
                    "metadata": metadata,
                },
            )
        )

    ranked.sort(
        key=lambda item: item[0],
        reverse=True,
    )

    return ranked


# ============================================================
# SEARCH CHUNKS
# ============================================================

def search_chunks(
    user_id: int,
    question_embedding: Sequence[float],
    n_results: int = 10,
    query_text: Optional[str] = None,
    min_distance: Optional[float] = DEFAULT_MIN_DISTANCE,
) -> Dict[str, Any]:
    """
    Semantic retrieval with conservative lexical reranking.

    Existing callers can continue using:

        search_chunks(
            user_id,
            question_embedding,
            n_results
        )

    Optional query_text improves ranking for terminology-heavy
    questions, especially OCR/scanned PDFs.

    No distance threshold is applied by default.
    """

    user_id = _validate_user_id(
        user_id
    )

    try:
        n_results = int(
            n_results
        )
    except (
        TypeError,
        ValueError,
    ) as error:
        raise ValueError(
            "n_results must be an integer."
        ) from error

    if n_results <= 0:
        raise ValueError(
            "n_results must be greater than 0."
        )

    query_embedding = (
        _embedding_to_list(
            question_embedding,
            0,
        )
    )

    query_dimension = len(
        query_embedding
    )

    collection = get_collection(
        user_id
    )

    try:
        total_vectors = (
            collection.count()
        )
    except Exception as error:
        print(
            "[VectorStore] Failed to read collection:",
            repr(error),
        )

        raise RuntimeError(
            "Unable to read ChromaDB collection."
        ) from error

    if total_vectors == 0:
        print(
            "[VectorStore] Collection is empty."
        )

        return {
            "ids": [[]],
            "documents": [[]],
            "metadatas": [[]],
            "distances": [[]],
        }

    # --------------------------------------------------------
    # Retrieve extra candidates.
    #
    # We intentionally retrieve more than the final requested
    # number when possible so lexical reranking has enough
    # candidates to work with.
    # --------------------------------------------------------

    candidate_count = min(
        max(
            n_results * 2,
            DEFAULT_SEARCH_RESULTS,
        ),
        total_vectors,
    )

    print()
    print(
        "[VectorStore] Semantic search:"
    )
    print(
        f"  User ID          : {user_id}"
    )
    print(
        f"  Query dimension  : {query_dimension}"
    )
    print(
        f"  Requested results: {n_results}"
    )
    print(
        f"  Candidates       : {candidate_count}"
    )
    print(
        f"  Collection size  : {total_vectors}"
    )

    if query_text:
        print(
            "[VectorStore] Query text       : "
            f"{str(query_text).strip()[:180]}"
        )

    # --------------------------------------------------------
    # Chroma query
    # --------------------------------------------------------

    try:
        results = collection.query(
            query_embeddings=[
                query_embedding
            ],
            n_results=candidate_count,
            include=[
                "documents",
                "metadatas",
                "distances",
            ],
        )

    except Exception as error:
        print(
            "[VectorStore] ChromaDB search failed:",
            repr(error),
        )

        raise RuntimeError(
            "Unable to search ChromaDB."
        ) from error

    result_documents = (
        results.get(
            "documents",
            [[]],
        )
        or [[]]
    )

    result_metadatas = (
        results.get(
            "metadatas",
            [[]],
        )
        or [[]]
    )

    result_distances = (
        results.get(
            "distances",
            [[]],
        )
        or [[]]
    )

    result_ids = (
        results.get(
            "ids",
            [[]],
        )
        or [[]]
    )

    documents = (
        result_documents[0]
        if result_documents
        else []
    )

    metadatas = (
        result_metadatas[0]
        if result_metadatas
        else []
    )

    distances = (
        result_distances[0]
        if result_distances
        else []
    )

    ids = (
        result_ids[0]
        if result_ids
        else []
    )

    print(
        "[VectorStore] Search returned "
        f"{len(documents)} candidate(s)."
    )

    if not documents:
        return {
            "ids": [[]],
            "documents": [[]],
            "metadatas": [[]],
            "distances": [[]],
        }

    # --------------------------------------------------------
    # Optional distance threshold
    # --------------------------------------------------------

    eligible_indices: List[int] = []

    for index, document in enumerate(
        documents
    ):
        distance = (
            distances[index]
            if index < len(distances)
            else None
        )

        if (
            min_distance is not None
            and distance is not None
            and _safe_float(
                distance,
                999.0,
            ) > float(min_distance)
        ):
            print(
                "[VectorStore] Candidate "
                f"{index + 1} rejected by "
                "distance threshold."
            )
            continue

        eligible_indices.append(
            index
        )

    # --------------------------------------------------------
    # Never return an accidental empty context only because
    # an optional threshold was too strict.
    # --------------------------------------------------------

    if (
        not eligible_indices
        and documents
    ):
        print(
            "[VectorStore] Distance threshold "
            "removed all candidates; "
            "restoring semantic candidates."
        )

        eligible_indices = list(
            range(len(documents))
        )

    filtered_documents = [
        documents[index]
        for index in eligible_indices
    ]

    filtered_metadatas = [
        (
            metadatas[index]
            if index < len(metadatas)
            else {}
        )
        for index in eligible_indices
    ]

    filtered_distances = [
        (
            distances[index]
            if index < len(distances)
            else None
        )
        for index in eligible_indices
    ]

    filtered_ids = [
        (
            ids[index]
            if index < len(ids)
            else ""
        )
        for index in eligible_indices
    ]

    # --------------------------------------------------------
    # Combined semantic + lexical ranking
    # --------------------------------------------------------

    ranked = _build_ranked_results(
        documents=filtered_documents,
        metadatas=filtered_metadatas,
        distances=filtered_distances,
        ids=filtered_ids,
        query_text=query_text,
    )

    # --------------------------------------------------------
    # Final results
    # --------------------------------------------------------

    final_limit = min(
        n_results,
        len(ranked),
    )

    selected = ranked[
        :final_limit
    ]

    output_documents: List[str] = []
    output_metadatas: List[
        Dict[str, Any]
    ] = []
    output_distances: List[
        Optional[float]
    ] = []
    output_ids: List[str] = []

    print(
        "[VectorStore] Final ranked results:"
    )

    for rank, (
        combined_score,
        _index,
        diagnostic,
    ) in enumerate(
        selected,
        start=1,
    ):
        metadata = diagnostic[
            "metadata"
        ]

        selected_id = (
            diagnostic.get(
                "id"
            )
        )

        # The source document corresponding to the selected
        # ranking item.
        original_index = ranked[
            rank - 1
        ][1]

        selected_document = (
            filtered_documents[
                original_index
            ]
        )

        selected_distance = (
            filtered_distances[
                original_index
            ]
            if original_index
            < len(filtered_distances)
            else None
        )

        output_documents.append(
            selected_document
        )

        output_metadatas.append(
            metadata
        )

        output_distances.append(
            selected_distance
        )

        if selected_id is not None:
            output_ids.append(
                selected_id
            )

        print(
            f"  {rank}. "
            f"{metadata.get('filename', 'Unknown')} "
            f"| page(s)="
            f"{metadata.get('page_numbers', 'unknown')} "
            f"| distance="
            f"{diagnostic['distance']} "
            f"| semantic="
            f"{diagnostic['semantic_score']} "
            f"| lexical="
            f"{diagnostic['lexical_overlap']} "
            f"| combined="
            f"{combined_score:.4f}"
        )

    return {
        "ids": [
            output_ids
        ],
        "documents": [
            output_documents
        ],
        "metadatas": [
            output_metadatas
        ],
        "distances": [
            output_distances
        ],
    }


# ============================================================
# DELETE DOCUMENT EMBEDDINGS
# ============================================================

def delete_pdf_embeddings(
    user_id: int,
    filename: str,
) -> int:
    """
    Delete all indexed vectors for one PDF.
    """

    user_id = _validate_user_id(
        user_id
    )

    filename = _clean_filename(
        filename
    )

    collection = get_collection(
        user_id
    )

    try:
        existing = collection.get(
            where={
                "filename": filename
            },
            include=["metadatas"],
        )

        ids = (
            existing.get(
                "ids",
                [],
            )
            if existing
            else []
        )

        if not ids:
            print(
                "[VectorStore] No vectors "
                f"found for: {filename}"
            )
            return 0

        collection.delete(
            ids=ids
        )

        print(
            "[VectorStore] Deleted "
            f"{len(ids)} vector(s) "
            f"for '{filename}'."
        )

        return len(ids)

    except Exception as error:
        print(
            "[VectorStore] Failed to delete vectors:",
            repr(error),
        )

        raise RuntimeError(
            "Unable to delete document vectors."
        ) from error


# ============================================================
# GET DOCUMENT SOURCE PAGES
# ============================================================

def get_document_source_pages(
    user_id: int,
    filename: str,
) -> List[int]:
    """
    Return all unique source pages represented by indexed chunks.
    """

    user_id = _validate_user_id(
        user_id
    )

    filename = _clean_filename(
        filename
    )

    collection = get_collection(
        user_id
    )

    try:
        result = collection.get(
            where={
                "filename": filename
            },
            include=["metadatas"],
        )

    except Exception as error:
        print(
            "[VectorStore] Failed to retrieve "
            "document source pages:",
            repr(error),
        )

        raise RuntimeError(
            "Unable to retrieve document source pages."
        ) from error

    metadatas = (
        result.get(
            "metadatas",
            [],
        )
        if result
        else []
    )

    pages: List[int] = []

    for metadata in metadatas:
        if not metadata:
            continue

        page_numbers = str(
            metadata.get(
                "page_numbers",
                "",
            )
            or ""
        )

        for value in page_numbers.split(
            ","
        ):
            page = _safe_int(
                value.strip(),
                0,
            )

            if (
                page > 0
                and page not in pages
            ):
                pages.append(page)

    return sorted(
        pages
    )


# ============================================================
# GET DOCUMENT STATISTICS
# ============================================================

def get_document_stats(
    user_id: int,
    filename: str,
) -> Dict[str, Any]:
    """
    Return indexed chunk, character and page statistics.
    """

    user_id = _validate_user_id(
        user_id
    )

    filename = _clean_filename(
        filename
    )

    collection = get_collection(
        user_id
    )

    try:
        result = collection.get(
            where={
                "filename": filename
            },
            include=[
                "metadatas",
                "documents",
            ],
        )

    except Exception as error:
        print(
            "[VectorStore] Failed to retrieve "
            "document stats:",
            repr(error),
        )

        raise RuntimeError(
            "Unable to retrieve document statistics."
        ) from error

    documents = (
        result.get(
            "documents",
            [],
        )
        if result
        else []
    )

    metadatas = (
        result.get(
            "metadatas",
            [],
        )
        if result
        else []
    )

    pages: List[int] = []

    characters = sum(
        len(
            str(
                document
                or ""
            )
        )
        for document in documents
    )

    for metadata in metadatas:
        if not metadata:
            continue

        page_values = str(
            metadata.get(
                "page_numbers",
                "",
            )
            or ""
        ).split(",")

        for value in page_values:
            page = _safe_int(
                value.strip(),
                0,
            )

            if (
                page > 0
                and page not in pages
            ):
                pages.append(page)

    pages.sort()

    return {
        "user_id": user_id,
        "filename": filename,
        "chunks": len(
            documents
        ),
        "characters": characters,
        "pages": pages,
        "page_count": len(
            pages
        ),
    }


# ============================================================
# DOCUMENT INSPECTION
# ============================================================

def inspect_document(
    user_id: int,
    filename: str,
    max_chunks: int = 10,
) -> List[
    Dict[str, Any]
]:
    """
    Return a compact read-only inspection of indexed chunks.

    Useful while debugging OCR/chunking/RAG problems.
    """

    user_id = _validate_user_id(
        user_id
    )

    filename = _clean_filename(
        filename
    )

    try:
        max_chunks = max(
            1,
            int(
                max_chunks
            ),
        )
    except (
        TypeError,
        ValueError,
    ):
        max_chunks = 10

    collection = get_collection(
        user_id
    )

    try:
        result = collection.get(
            where={
                "filename": filename
            },
            include=[
                "documents",
                "metadatas",
            ],
        )

    except Exception as error:
        print(
            "[VectorStore] Failed to inspect document:",
            repr(error),
        )

        raise RuntimeError(
            "Unable to inspect document."
        ) from error

    documents = (
        result.get(
            "documents",
            [],
        )
        if result
        else []
    )

    metadatas = (
        result.get(
            "metadatas",
            [],
        )
        if result
        else []
    )

    # Chroma's get order is not guaranteed to be the original
    # insertion order. Sort chunks by their stored chunk index.
    rows_with_index: List[
        Tuple[int, Dict[str, Any]]
    ] = []

    for index, document in enumerate(
        documents
    ):
        metadata = (
            metadatas[index]
            if index < len(
                metadatas
            )
            else {}
        ) or {}

        chunk_index = _safe_int(
            metadata.get(
                "chunk_index",
                index,
            ),
            index,
        )

        rows_with_index.append(
            (
                chunk_index,
                {
                    "chunk_index": chunk_index,
                    "page_number": metadata.get(
                        "page_number",
                        0,
                    ),
                    "page_numbers": metadata.get(
                        "page_numbers",
                        "",
                    ),
                    "characters": len(
                        str(
                            document
                            or ""
                        )
                    ),
                    "preview": str(
                        document
                        or ""
                    )[:500],
                },
            )
        )

    rows_with_index.sort(
        key=lambda item: item[0]
    )

    return [
        row
        for _, row in rows_with_index[
            :max_chunks
        ]
    ]


# ============================================================
# COLLECTION STATISTICS
# ============================================================

def get_collection_stats(
    user_id: int,
) -> dict:
    """
    Return statistics for the authenticated user's collection.
    """

    user_id = _validate_user_id(
        user_id
    )

    collection = get_collection(
        user_id
    )

    try:
        total_vectors = (
            collection.count()
        )

    except Exception as error:
        print(
            "[VectorStore] Failed to get "
            "collection stats:",
            repr(error),
        )

        raise RuntimeError(
            "Unable to read collection statistics."
        ) from error

    return {
        "user_id": user_id,
        "collection": (
            _get_collection_name(
                user_id
            )
        ),
        "total_vectors": total_vectors,
        "database_path": CHROMA_DB_PATH,
        "distance_metric": "cosine",
    }


# ============================================================
# VECTOR STORE TEST
# ============================================================

def test_vector_store() -> None:
    """
    Basic end-to-end vector store test.

    This uses a dedicated temporary test user and deletes its
    vectors afterward.
    """

    print()
    print("=" * 72)
    print(
        "STUDYSPHERE VECTOR STORE TEST"
    )
    print("=" * 72)

    test_user_id = 999999
    test_filename = (
        "__vector_store_test__.pdf"
    )

    test_chunks = [
        (
            "[Page 10]\n"
            "Software testing is the process "
            "of evaluating software."
        ),
        (
            "[Page 11]\n"
            "Verification checks whether "
            "software is built correctly."
        ),
        (
            "[Page 12]\n"
            "Validation checks whether "
            "the correct software is built."
        ),
    ]

    try:
        from services.embedding import (
            generate_embeddings,
            generate_query_embedding,
        )

        print(
            "[VectorStore Test] Generating embeddings..."
        )

        embeddings = generate_embeddings(
            test_chunks
        )

        stored = store_chunks(
            user_id=test_user_id,
            filename=test_filename,
            chunks=test_chunks,
            embeddings=embeddings,
        )

        print(
            f"Stored vectors: {stored}"
        )

        query_embedding = (
            generate_query_embedding(
                "What is verification?"
            )
        )

        results = search_chunks(
            user_id=test_user_id,
            question_embedding=query_embedding,
            n_results=3,
            query_text=(
                "What is verification?"
            ),
        )

        print()
        print(
            "Search results:"
        )

        documents = results.get(
            "documents",
            [[]],
        )

        metadatas = results.get(
            "metadatas",
            [[]],
        )

        if (
            documents
            and documents[0]
        ):
            for index, document in enumerate(
                documents[0],
                start=1,
            ):
                metadata = (
                    metadatas[0][
                        index - 1
                    ]
                    if (
                        metadatas
                        and metadatas[0]
                        and index - 1
                        < len(
                            metadatas[0]
                        )
                    )
                    else {}
                )

                print(
                    f"{index}. {document}"
                )

                print(
                    "   Source: "
                    f"{metadata.get(
                        'filename',
                        'Unknown'
                    )}"
                )

                print(
                    "   Page(s): "
                    f"{metadata.get(
                        'page_numbers',
                        'Unknown'
                    )}"
                )

        source_pages = (
            get_document_source_pages(
                user_id=test_user_id,
                filename=test_filename,
            )
        )

        print()
        print(
            "Source pages:"
        )
        print(
            source_pages
        )

        print()
        print(
            "Document stats:"
        )
        print(
            get_document_stats(
                test_user_id,
                test_filename,
            )
        )

        print()
        print(
            "Document inspection:"
        )
        print(
            inspect_document(
                test_user_id,
                test_filename,
                max_chunks=10,
            )
        )

        print()
        print(
            "Vector store test completed successfully."
        )

    finally:
        try:
            deleted = (
                delete_pdf_embeddings(
                    user_id=test_user_id,
                    filename=test_filename,
                )
            )

            print()
            print(
                "Deleted test vectors: "
                f"{deleted}"
            )

        except Exception as cleanup_error:
            print(
                "[VectorStore Test] Cleanup failed:",
                repr(cleanup_error),
            )

    print()
    print("=" * 72)


# ============================================================
# MODULE INFORMATION
# ============================================================

def get_vector_store_info() -> dict:
    """
    Return module configuration and capabilities.
    """

    return {
        "database_path": CHROMA_DB_PATH,
        "collection_prefix": COLLECTION_PREFIX,
        "batch_size": BATCH_SIZE,
        "distance_metric": "cosine",
        "page_metadata": True,
        "document_replacement": True,
        "diagnostic_search": True,
        "lexical_reranking": True,
        "document_stats": True,
        "ocr_friendly_retrieval": True,
    }